import type {
  ConfigScalar,
  NormalizedMigration,
  NormalizedRecord,
  ProviderRef
} from "./normalize.js";

export function emitConfig(migration: NormalizedMigration): string {
  const imports = collectImports(migration.keys);
  return [
    "// Generated by @keyshelf/migrate from v4 keyshelf.yaml and .keyshelf/*.yaml.",
    "// Review groups, provider bindings, and the secret rebind commands in the migration report.",
    "",
    `import { ${imports.join(", ")} } from "keyshelf/config";`,
    "",
    "export default defineConfig({",
    `  name: ${literal(migration.name)},`,
    `  envs: ${arrayLiteral(migration.envs)},`,
    "  // TODO: Add v5 groups and assign group names to records as needed.",
    "  groups: [],",
    "  keys: {",
    ...migration.keys.flatMap((record) => emitRecord(record)),
    "  }",
    "});",
    ""
  ].join("\n");
}

function collectImports(records: NormalizedRecord[]): string[] {
  const imports = new Set(["defineConfig"]);
  for (const record of records) {
    if (record.kind === "config" && shouldUseConfigFactory(record)) {
      imports.add("config");
    }
    if (record.kind === "secret") {
      imports.add("secret");
      for (const provider of providerRefs(record)) {
        imports.add(provider.name);
      }
    }
  }
  return [...imports].sort((a, b) => {
    if (a === "defineConfig") return -1;
    if (b === "defineConfig") return 1;
    return a.localeCompare(b);
  });
}

function emitRecord(record: NormalizedRecord): string[] {
  const key = literal(record.path);
  if (record.kind === "config") {
    if (!shouldUseConfigFactory(record) && record.default !== undefined) {
      return [`    ${key}: ${literal(record.default)},`];
    }

    return [`    ${key}: config(${objectLiteral(recordFields(record), 4)}),`];
  }

  return [`    ${key}: secret(${objectLiteral(recordFields(record), 4)}),`];
}

function recordFields(record: NormalizedRecord): Record<string, unknown> {
  if (record.kind === "config") {
    return {
      ...(record.default !== undefined ? { default: record.default } : {}),
      ...(record.values !== undefined ? { values: record.values } : {})
    };
  }

  return {
    ...(record.optional ? { optional: true } : {}),
    ...(record.default !== undefined ? { default: record.default } : {}),
    ...(record.values !== undefined ? { values: record.values } : {})
  };
}

function shouldUseConfigFactory(record: Extract<NormalizedRecord, { kind: "config" }>): boolean {
  return record.values !== undefined || record.default === undefined;
}

function providerRefs(record: Extract<NormalizedRecord, { kind: "secret" }>): ProviderRef[] {
  return [
    ...(record.default !== undefined ? [record.default] : []),
    ...Object.values(record.values ?? {})
  ];
}

function objectLiteral(value: Record<string, unknown>, indent: number): string {
  const entries = Object.entries(value);
  if (entries.length === 0) return "{}";

  const spaces = " ".repeat(indent);
  const childSpaces = " ".repeat(indent + 2);
  return [
    "{",
    ...entries.map(([key, entry]) => `${childSpaces}${key}: ${valueLiteral(entry, indent + 2)},`),
    `${spaces}}`
  ].join("\n");
}

function valueLiteral(value: unknown, indent: number): string {
  if (isProviderRef(value)) {
    return `${value.name}(${objectLiteral(value.options, indent)})`;
  }
  if (Array.isArray(value)) {
    return arrayLiteral(value);
  }
  if (value != null && typeof value === "object") {
    return objectLiteral(value as Record<string, unknown>, indent);
  }
  return literal(value as ConfigScalar);
}

function arrayLiteral(values: unknown[]): string {
  return `[${values.map((value) => valueLiteral(value, 0)).join(", ")}]`;
}

function literal(value: ConfigScalar): string {
  return JSON.stringify(value);
}

function isProviderRef(value: unknown): value is ProviderRef {
  return (
    value != null &&
    typeof value === "object" &&
    "name" in value &&
    "options" in value &&
    typeof (value as ProviderRef).name === "string"
  );
}
